// <auto-generated />
using System;
using Linuxdle.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Linuxdle.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LinuxdleDbContext))]
    partial class LinuxdleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyCommandDailyCommandCategory", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer")
                        .HasColumnName("categories_id");

                    b.Property<int>("CommandsId")
                        .HasColumnType("integer")
                        .HasColumnName("commands_id");

                    b.HasKey("CategoriesId", "CommandsId")
                        .HasName("pk_daily_command_daily_command_category");

                    b.HasIndex("CommandsId")
                        .HasDatabaseName("ix_daily_command_daily_command_category_commands_id");

                    b.ToTable("daily_command_daily_command_category", (string)null);
                });

            modelBuilder.Entity("Linuxdle.Domain.DailyCommands.DailyCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<bool>("IsPosix")
                        .HasColumnType("boolean")
                        .HasColumnName("is_posix");

                    b.Property<int>("ManSection")
                        .HasColumnType("integer")
                        .HasColumnName("man_section");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("OriginYear")
                        .HasColumnType("integer")
                        .HasColumnName("origin_year");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("package");

                    b.Property<bool>("RequiresArgs")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_args");

                    b.HasKey("Id")
                        .HasName("pk_daily_commands");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_commands_name");

                    b.ToTable("daily_commands", (string)null);
                });

            modelBuilder.Entity("Linuxdle.Domain.DailyCommands.DailyCommandCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_daily_command_categories");

                    b.ToTable("daily_command_categories", (string)null);
                });

            modelBuilder.Entity("Linuxdle.Domain.DailyDistros.DailyDistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseDistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("base_distro");

                    b.Property<string>("DefaultDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_de");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("logo_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_daily_distros");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_distros_slug");

                    b.ToTable("daily_distros", (string)null);
                });

            modelBuilder.Entity("Linuxdle.Domain.DailyPuzzles.DailyPuzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_daily_puzzles");

                    b.HasIndex("GameId", "ScheduledDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_puzzles_game_id_scheduled_date");

                    b.ToTable("daily_puzzles", (string)null);
                });

            modelBuilder.Entity("Linuxdle.Domain.Games.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_games_name");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Linuxdle.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastRefreshAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refresh_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("refresh_token");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_expiration_valid", "expires_at > last_refresh_at");
                        });
                });

            modelBuilder.Entity("DailyCommandDailyCommandCategory", b =>
                {
                    b.HasOne("Linuxdle.Domain.DailyCommands.DailyCommandCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_command_daily_command_category_daily_command_categori");

                    b.HasOne("Linuxdle.Domain.DailyCommands.DailyCommand", null)
                        .WithMany()
                        .HasForeignKey("CommandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_command_daily_command_category_daily_commands_command");
                });

            modelBuilder.Entity("Linuxdle.Domain.DailyPuzzles.DailyPuzzle", b =>
                {
                    b.HasOne("Linuxdle.Domain.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_puzzles_games_game_id");

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
