name: "Commit Message Check"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - main
      - master

jobs:
  commitlint:
    name: Validate Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs