name: Build and Deploy

on:
  push:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  # e.g. RealOrangeKun
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - context: ./backend
            image_name: linuxdle-backend
          - context: ./frontend
            image_name: linuxdle-frontend
            target: production
          - context: ./gateway
            image_name: linuxdle-gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lowercase the repo owner name
        run: |
          echo "OWNER_LOWER=$(echo ${{ env.OWNER }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          target: ${{ matrix.target }}
          push: true
          # Resulting tag: ghcr.io/realorangekun/linuxdle-backend:latest
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LOWER }}/${{ matrix.image_name }}:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy Local
        run: |
          cd /home/yousseftarek/Projects/linuxdle
          # Pull latest code (compose files, configs, etc.)
          git pull origin master
          # Authenticate to GHCR using the temporary GITHUB_TOKEN
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # Pull latest images
          docker compose -f docker-compose.prod.yml pull
          # Restart services
          docker compose -f docker-compose.prod.yml up -d
          # Clean up old/dangling images to save disk space
          docker image prune -f
